/**
 * WorkflowDetailPage — layer 2 inside a specific workflow type (e.g. 爆款仿写).
 *
 * Hero section prominently surfaces NoobClaw's differentiators:
 *   - Real Chrome + real login
 *   - No debugger yellow banner
 *   - Fixed prompts, 10x cheaper tokens
 *   - BYOK — user brings their own Anthropic key
 *   - Hard-wired safety rails
 *   - Shared viral pool
 *
 * Below the hero: scenario grid + existing tasks for this workflow.
 */

import React from 'react';
import { i18nService } from '../../services/i18n';
import type { Scenario, Task, Draft } from '../../services/scenario';

interface Props {
  workflow_type: string;
  scenarios: Scenario[];
  tasks: Task[];
  draftsByTask: Map<string, Draft[]>;
  onBack: () => void;
  onConfigure: (scenario: Scenario) => void;
  onOpenTask: (task_id: string) => void;
}

type Advantage = {
  icon: string;
  titleKey: string;
  descKey: string;
};

const ADVANTAGES: Advantage[] = [
  {
    icon: '🛡️',
    titleKey: 'scenarioAdvantageRealChromeTitle',
    descKey: 'scenarioAdvantageRealChromeDesc',
  },
  {
    icon: '🤖',
    titleKey: 'scenarioAdvantageAutoGenerateTitle',
    descKey: 'scenarioAdvantageAutoGenerateDesc',
  },
  {
    icon: '🚀',
    titleKey: 'scenarioAdvantageAutoUploadTitle',
    descKey: 'scenarioAdvantageAutoUploadDesc',
  },
  {
    icon: '💰',
    titleKey: 'scenarioAdvantageFixedPromptTitle',
    descKey: 'scenarioAdvantageFixedPromptDesc',
  },
  {
    icon: '🌊',
    titleKey: 'scenarioAdvantagePoolTitle',
    descKey: 'scenarioAdvantagePoolDesc',
  },
];

export const WorkflowDetailPage: React.FC<Props> = ({
  scenarios,
  tasks,
  draftsByTask,
  onBack,
  onConfigure,
  onOpenTask,
}) => {
  const installedScenarioIds = new Set(tasks.map(t => t.scenario_id));
  const taskByScenarioId = new Map(tasks.map(t => [t.scenario_id, t]));

  return (
    <div className="p-6 max-w-6xl mx-auto">
      {/* Back button */}
      <button
        type="button"
        onClick={onBack}
        className="mb-6 inline-flex items-center gap-1 text-sm text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors"
      >
        ← {i18nService.t('scenarioTaskBack')}
      </button>

      {/* Hero — NoobClaw advantages */}
      <div className="relative rounded-3xl border border-green-500/20 bg-gradient-to-br from-green-500/10 via-emerald-500/5 to-transparent p-8 mb-10 overflow-hidden">
        {/* Subtle decorative glow */}
        <div className="absolute -top-24 -right-24 w-64 h-64 rounded-full bg-green-500/10 blur-3xl pointer-events-none" />

        <div className="relative">
          <div className="flex items-center gap-2 text-xs font-medium text-green-500 mb-3">
            <span className="inline-block w-1.5 h-1.5 rounded-full bg-green-500" />
            {i18nService.t('scenarioWorkflowAvailable')} · 🔥 {i18nService.t('scenarioWorkflowViral')}
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold dark:text-white mb-3 leading-tight">
            {i18nService.t('scenarioHeroTitle')}
          </h1>
          <p className="text-base text-gray-600 dark:text-gray-300 max-w-3xl leading-relaxed">
            {i18nService.t('scenarioHeroSubtitle')}
          </p>

          <div className="mt-8">
            <div className="text-xs font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-4">
              ✨ {i18nService.t('scenarioAdvantageTitle')}
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              {ADVANTAGES.map(adv => (
                <div
                  key={adv.titleKey}
                  className="rounded-xl border border-gray-200/80 dark:border-gray-700/50 bg-white/60 dark:bg-gray-900/40 backdrop-blur-sm p-4"
                >
                  <div className="text-xl mb-2">{adv.icon}</div>
                  <div className="font-semibold text-sm dark:text-white mb-1.5">
                    {i18nService.t(adv.titleKey)}
                  </div>
                  <div className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed">
                    {i18nService.t(adv.descKey)}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Scenario grid */}
      <section>
        <h2 className="text-sm font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-4">
          📚 {i18nService.t('scenarioSectionScenarios')}
        </h2>

        {scenarios.length === 0 ? (
          <div className="rounded-xl border border-dashed border-gray-300 dark:border-gray-700 p-6 text-center text-sm text-gray-500 dark:text-gray-400">
            {i18nService.t('scenarioWorkflowComingSoon')}
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {scenarios.map(s => {
              const installed = installedScenarioIds.has(s.id);
              const task = taskByScenarioId.get(s.id);
              const pendingCount = task
                ? (draftsByTask.get(task.id) || []).filter(d => d.status === 'pending').length
                : 0;
              return (
                <div
                  key={s.id}
                  className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 p-5 hover:shadow-lg hover:border-green-500/50 dark:hover:border-green-500/50 transition-all"
                >
                  <div className="text-3xl mb-3">{s.icon || '📝'}</div>
                  <div className="font-semibold dark:text-white mb-1">{s.name_zh}</div>
                  <div className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed mb-4 min-h-[3rem] line-clamp-3">
                    {s.description_zh}
                  </div>
                  <div className="flex items-center gap-2">
                    {installed && task ? (
                      <>
                        <button
                          type="button"
                          onClick={() => onOpenTask(task.id)}
                          className="flex-1 text-xs font-medium px-3 py-2 rounded-lg bg-green-500/10 text-green-500 border border-green-500/30 hover:bg-green-500/20 transition-colors"
                        >
                          {i18nService.t('scenarioCardOpen')}
                          {pendingCount > 0 && (
                            <span className="ml-1">
                              ·{' '}
                              {i18nService
                                .t('scenarioCardTaskDraftCount')
                                .replace('{n}', String(pendingCount))}
                            </span>
                          )}
                        </button>
                        <button
                          type="button"
                          onClick={() => onConfigure(s)}
                          className="text-xs font-medium px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-700 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                        >
                          {i18nService.t('scenarioCardEdit')}
                        </button>
                      </>
                    ) : (
                      <button
                        type="button"
                        onClick={() => onConfigure(s)}
                        className="flex-1 text-xs font-medium px-3 py-2 rounded-lg bg-gray-900 dark:bg-white text-white dark:text-gray-900 hover:opacity-90 transition-opacity"
                      >
                        {i18nService.t('scenarioCardConfigure')}
                      </button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </section>
    </div>
  );
};

export default WorkflowDetailPage;
