/**
 * XhsWorkflowsPage — layer 1 inside 小红书 tab.
 *
 * Sections (top-down):
 *   1. Quick-start banner for 爆款仿写 (one-click with login gate)
 *   2. NoobClaw 5 advantages hero (moved from the old WorkflowDetailPage)
 *   3. "My tasks" list (collapsed card per task)
 *   4. Workflow-type grid (爆款仿写 active, 4 coming soon)
 *
 * The top banner is the "一键按钮" users were looking for. It:
 *   - Checks XHS login via scenarioService.checkXhsLogin
 *   - Shows LoginRequiredModal if not logged in
 *   - If no task yet, opens the config wizard for the first available
 *     xhs_viral_production scenario
 *   - If a task already exists, jumps straight to its task detail page
 */

import React, { useState } from 'react';
import { i18nService } from '../../services/i18n';
import { type Scenario, type Task, type Draft } from '../../services/scenario';
import { LoginRequiredModal } from './LoginRequiredModal';
import type { XhsLoginStatus } from '../../types/scenario';

type WorkflowDef = {
  id: string;
  icon: string;
  titleKey: string;
  descKey: string;
  available: boolean;
};

const WORKFLOWS: WorkflowDef[] = [
  { id: 'viral_production', icon: '🔥', titleKey: 'scenarioWorkflowViral', descKey: 'scenarioWorkflowViralDesc', available: true },
  { id: 'auto_reply', icon: '💬', titleKey: 'scenarioWorkflowAutoReply', descKey: 'scenarioWorkflowAutoReplyDesc', available: false },
  { id: 'mass_comment', icon: '🎯', titleKey: 'scenarioWorkflowMassComment', descKey: 'scenarioWorkflowMassCommentDesc', available: false },
  { id: 'dm_reply', icon: '📬', titleKey: 'scenarioWorkflowDmReply', descKey: 'scenarioWorkflowDmRelyDesc', available: false },
  { id: 'data_monitor', icon: '📈', titleKey: 'scenarioWorkflowDataMonitor', descKey: 'scenarioWorkflowDataMonitorDesc', available: false },
];

const ADVANTAGES: Array<{ icon: string; titleKey: string; descKey: string }> = [
  { icon: '🛡️', titleKey: 'scenarioAdvantageRealChromeTitle', descKey: 'scenarioAdvantageRealChromeDesc' },
  { icon: '🤖', titleKey: 'scenarioAdvantageAutoGenerateTitle', descKey: 'scenarioAdvantageAutoGenerateDesc' },
  { icon: '🚀', titleKey: 'scenarioAdvantageAutoUploadTitle', descKey: 'scenarioAdvantageAutoUploadDesc' },
  { icon: '💰', titleKey: 'scenarioAdvantageFixedPromptTitle', descKey: 'scenarioAdvantageFixedPromptDesc' },
  { icon: '🌊', titleKey: 'scenarioAdvantagePoolTitle', descKey: 'scenarioAdvantagePoolDesc' },
];

interface Props {
  scenarios: Scenario[];
  tasks: Task[];
  draftsByTask: Map<string, Draft[]>;
  loading: boolean;
  onOpenWorkflow: (workflow_type: string) => void;
  onOpenTask: (task_id: string) => void;
  onConfigure: (scenario: Scenario) => void;
}

export const XhsWorkflowsPage: React.FC<Props> = ({
  scenarios,
  tasks,
  draftsByTask,
  loading,
  onOpenWorkflow,
  onOpenTask,
  onConfigure,
}) => {
  const scenarioById = new Map(scenarios.map(s => [s.id, s]));
  const [loginModalReason, setLoginModalReason] = useState<string | null>(null);

  // Find the default viral-production scenario. If the backend scenario list
  // hasn't loaded yet, use a hardcoded fallback so the "立即开始" button
  // ALWAYS opens the config wizard — never navigates to an empty sub-page.
  const FALLBACK_SCENARIO: Scenario = {
    id: 'xhs_viral_production_career',
    version: '1.0.0',
    platform: 'xhs',
    workflow_type: 'viral_production',
    category: 'knowledge',
    name_zh: '副业干货',
    name_en: 'Side Hustle Notes',
    description_zh: '自动发现小红书副业图文爆款，本地 AI 拆解后用你的 persona 生成仿写。',
    description_en: 'Discover viral side-hustle image notes on Xiaohongshu.',
    icon: '💼',
    default_config: {
      keywords: ['副业', '下班赚钱', '兼职', '月入'],
      persona: '一个想在下班后搞点副业的普通打工人，真诚不装',
      daily_count: 3,
      variants_per_post: 3,
      schedule_window: '08:00-09:00',
    },
    risk_caps: {
      max_daily_runs: 1, max_scroll_per_run: 20,
      min_scroll_delay_ms: 1800, max_scroll_delay_ms: 4200,
      read_dwell_min_ms: 2500, read_dwell_max_ms: 5500,
      max_run_duration_ms: 720000, min_interval_hours: 8,
      weekly_rest_days: 1, cooldown_captcha_hours: 24,
      cooldown_rate_limit_hours: 48, cooldown_account_flag_hours: 72,
    },
    required_login_url: 'https://www.xiaohongshu.com',
    entry_urls: {},
    skills: {},
  };

  const primaryScenario = scenarios.find(
    s => s.platform === 'xhs' && s.workflow_type === 'viral_production'
  ) || FALLBACK_SCENARIO;

  const primaryTask = tasks.find(t => t.scenario_id === primaryScenario.id);

  const handleQuickStart = () => {
    if (primaryTask) {
      onOpenTask(primaryTask.id);
    } else {
      onConfigure(primaryScenario);
    }
  };

  const handleLoginRetry = (status: XhsLoginStatus) => {
    if (status.loggedIn) {
      setLoginModalReason(null);
      handleQuickStart();
    } else {
      setLoginModalReason(status.reason || 'not_logged_in');
    }
  };

  return (
    <div className="p-6 max-w-6xl mx-auto">
      {/* Quick-start banner — ALWAYS visible, even before scenario list loads */}
      <section className="mb-6">
        <div className="relative rounded-2xl border border-green-500/30 bg-gradient-to-br from-green-500/10 via-emerald-500/5 to-transparent p-6 sm:p-8 overflow-hidden">
          <div className="absolute -top-16 -right-16 w-48 h-48 rounded-full bg-green-500/10 blur-3xl pointer-events-none" />
          <div className="relative flex items-center justify-between gap-6 flex-wrap">
            <div className="flex-1 min-w-0">
              <div className="inline-flex items-center gap-1.5 text-xs font-medium text-green-500 mb-2">
                <span className="inline-block w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
                {i18nService.t('scenarioWorkflowAvailable')}
              </div>
              <h2 className="text-xl sm:text-2xl font-bold dark:text-white mb-1.5">
                🔥 {i18nService.t('scenarioQuickStartTitle')}
              </h2>
              <p className="text-sm text-gray-600 dark:text-gray-300 max-w-2xl leading-relaxed">
                {i18nService.t('scenarioQuickStartDesc')}
              </p>
            </div>
            <button
              type="button"
              onClick={handleQuickStart}
              className="shrink-0 px-8 py-4 text-base font-bold rounded-xl bg-green-500 text-white hover:bg-green-600 shadow-lg shadow-green-500/25 transition-all active:scale-95"
            >
              {primaryTask
                ? '📋 ' + i18nService.t('scenarioQuickStartContinueBtn') + ' →'
                : '🚀 ' + i18nService.t('scenarioQuickStartBtn') + ' →'}
            </button>
          </div>
        </div>
      </section>

      {/* NoobClaw advantages — compact inline pills (visually distinct from workflow cards) */}
      <section className="mb-6">
        <div className="flex flex-wrap items-center gap-2">
          {ADVANTAGES.map(adv => (
            <span
              key={adv.titleKey}
              title={i18nService.t(adv.descKey)}
              className="inline-flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-full border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50 text-gray-600 dark:text-gray-300 cursor-default"
            >
              <span>{adv.icon}</span>
              <span>{i18nService.t(adv.titleKey)}</span>
            </span>
          ))}
        </div>
      </section>

      {/* My tasks */}
      <section className="mb-8">
        <h2 className="text-sm font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-4">
          📌 {i18nService.t('scenarioSectionMyTasks')}
        </h2>
        {loading && tasks.length === 0 ? (
          <div className="text-sm text-gray-400 py-6">{i18nService.t('common.loading') || '加载中...'}</div>
        ) : tasks.length === 0 ? (
          <div className="rounded-xl border border-dashed border-gray-300 dark:border-gray-700 p-6 text-center text-sm text-gray-500 dark:text-gray-400">
            {i18nService.t('scenarioSectionNoTasks')}
          </div>
        ) : (
          <div className="space-y-2">
            {tasks.map(task => {
              const scenario = scenarioById.get(task.scenario_id);
              const taskDrafts = draftsByTask.get(task.id) || [];
              const pendingCount = taskDrafts.filter(d => d.status === 'pending').length;
              return (
                <button
                  key={task.id}
                  type="button"
                  onClick={() => onOpenTask(task.id)}
                  className="w-full text-left rounded-xl border border-gray-200 dark:border-gray-700 hover:border-green-500/50 dark:hover:border-green-500/50 bg-white dark:bg-gray-900 px-4 py-3 flex items-center gap-3 transition-colors"
                >
                  <div className="text-2xl">{scenario?.icon || '🔥'}</div>
                  <div className="flex-1 min-w-0">
                    <div className="font-medium dark:text-white truncate">
                      {scenario?.name_zh || task.scenario_id}
                    </div>
                    <div className="text-xs text-gray-500 dark:text-gray-400 truncate">
                      {task.keywords.join(' · ')}
                    </div>
                  </div>
                  <div className="flex items-center gap-2 shrink-0">
                    {task.enabled ? (
                      <span className="text-xs px-2 py-1 rounded bg-green-500/10 text-green-500 border border-green-500/30">
                        {i18nService.t('scenarioCardTaskRunning')}
                      </span>
                    ) : (
                      <span className="text-xs px-2 py-1 rounded bg-gray-200 dark:bg-gray-800 text-gray-500">
                        {i18nService.t('scenarioCardTaskPaused')}
                      </span>
                    )}
                    {pendingCount > 0 && (
                      <span className="text-xs px-2 py-1 rounded bg-amber-500/10 text-amber-500 border border-amber-500/30">
                        {i18nService.t('scenarioCardTaskDraftCount').replace('{n}', String(pendingCount))}
                      </span>
                    )}
                  </div>
                </button>
              );
            })}
          </div>
        )}
      </section>

      {/* Workflow grid */}
      <section>
        <h2 className="text-sm font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-4">
          🛠  {i18nService.t('scenarioPlatformXhs')} · {i18nService.t('scenarioSectionRun')}
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {WORKFLOWS.map(wf => (
            <button
              key={wf.id}
              type="button"
              onClick={() => (wf.available ? onOpenWorkflow(wf.id) : undefined)}
              disabled={!wf.available}
              className={`text-left rounded-2xl border p-5 transition-colors ${
                wf.available
                  ? 'border-gray-200 dark:border-gray-700 hover:border-green-500/50 hover:shadow-lg dark:hover:border-green-500/50 bg-white dark:bg-gray-900 cursor-pointer'
                  : 'border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-gray-900/50 opacity-60 cursor-not-allowed'
              }`}
            >
              <div className="text-4xl mb-3">{wf.icon}</div>
              <div className="font-semibold text-base dark:text-white mb-1.5">
                {i18nService.t(wf.titleKey)}
              </div>
              <div className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed mb-4 min-h-[2.5rem]">
                {i18nService.t(wf.descKey)}
              </div>
              <div>
                {wf.available ? (
                  <span className="inline-flex items-center gap-1.5 text-xs font-medium text-green-500">
                    <span className="w-1.5 h-1.5 rounded-full bg-green-500" />
                    {i18nService.t('scenarioWorkflowAvailable')}
                  </span>
                ) : (
                  <span className="inline-flex items-center gap-1.5 text-xs font-medium text-gray-400">
                    <span className="w-1.5 h-1.5 rounded-full bg-gray-400" />
                    {i18nService.t('scenarioWorkflowComingSoon')}
                  </span>
                )}
              </div>
            </button>
          ))}
        </div>
      </section>

      {loginModalReason && (
        <LoginRequiredModal
          reason={loginModalReason}
          onCancel={() => setLoginModalReason(null)}
          onRetry={handleLoginRetry}
        />
      )}
    </div>
  );
};

export default XhsWorkflowsPage;
